import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("options page exposes category settings, site assignment, rule management, and JSON editor modes", async () => {
  const html = await readFile(new URL("../extension/options/options.html", import.meta.url), "utf8");
  const script = await readFile(new URL("../extension/options/options.js", import.meta.url), "utf8");
  const css = await readFile(new URL("../extension/options/options.css", import.meta.url), "utf8");

  assert.match(html, /data-mode="builder"/);
  assert.match(html, /data-mode="board"/);
  assert.match(html, /data-mode="rules"/);
  assert.match(html, /data-mode="json"/);
  assert.match(html, /id="urlInput"/);
  assert.match(html, /id="parentFolderSelect"/);
  assert.match(html, /id="targetFolderSelect"/);
  assert.match(html, /id="targetIconSelect"/);
  assert.match(html, /id="candidateSourceSelect"/);
  assert.match(html, /id="candidateAxisPurpose"/);
  assert.match(html, /id="candidateAxisUsage"/);
  assert.match(html, /id="candidateAxisTheme"/);
  assert.match(html, /data-view="group"/);
  assert.match(html, /data-view="grid"/);
  assert.match(html, /data-view="list"/);
  assert.match(html, /data-site-view="grid"/);
  assert.match(html, /data-site-view="list"/);
  assert.match(html, /分類先設定/);
  assert.match(html, /サイト割り当て/);
  assert.match(html, /ルール管理/);
  assert.match(html, /サイト URL <span class="field-badge optional">任意/);
  assert.match(html, /id="loadSitesButton"/);
  assert.match(html, /id="hideAssignedSitesInput"/);
  assert.match(html, /id="categoryManagerList"/);
  assert.match(html, /id="categoryDropList"/);
  assert.match(html, /id="siteSourceList"/);
  assert.match(html, /id="ruleCards"/);
  assert.match(html, /id="rulesEditor"/);
  assert.match(html, /id="clearAllRulesButton"/);
  assert.match(html, /全ルール削除/);
  assert.match(html, /field-badge required/);
  assert.match(html, /field-badge optional/);
  assert.match(html, /form-row-main/);
  assert.match(html, /form-row-category/);
  assert.match(html, /form-row-detail/);
  assert.match(script, /SUGGEST_RULES_FROM_BOOKMARKS/);
  assert.match(script, /GET_SITE_RULE_SOURCES/);
  assert.match(script, /MODE_CONFIG/);
  assert.match(script, /RULE_VIEW_RENDERERS/);
  assert.match(script, /renderFlatRules/);
  assert.match(script, /getSelectedCandidateAxes/);
  assert.match(script, /materializeCandidateRule/);
  assert.match(script, /validateRule/);
  assert.match(script, /handleEditorInput/);
  assert.match(script, /applyEditorRules/);
  assert.match(script, /parseEditorRules/);
  assert.match(script, /elements\.editor\.addEventListener\("input"/);
  assert.match(script, /config\.syncBeforeEnter && !applyEditorRules/);
  assert.match(script, /hideAssignedSites/);
  assert.match(script, /truncateText/);
  assert.match(script, /createRuleFromUrl/);
  assert.match(script, /createCategoryDefinitionRule/);
  assert.match(script, /renderCategoryManager/);
  assert.match(script, /editCategory/);
  assert.match(script, /deleteCategory/);
  assert.match(script, /clearAllRules/);
  assert.match(script, /type:\s*"category"/);
  assert.doesNotMatch(script, /getCategoryOptions/);
  assert.match(script, /getAvailableCategoryOptions/);
  assert.match(script, /createCategoryOptionsFromRules/);
  assert.match(script, /mergeCategoryOptions/);
  assert.match(script, /renderAssignmentBoard/);
  assert.match(script, /assignSiteToCategory/);
  assert.match(script, /countCategoryRules/);
  assert.match(script, /getDomainRuleForSite/);
  assert.match(script, /dragover/);
  assert.match(script, /dataTransfer\.setData/);
  assert.match(script, /setRuleView/);
  assert.match(script, /setSiteView/);
  assert.match(script, /isImageIcon/);
  assert.match(script, /createSiteThumbnail/);
  assert.match(script, /buildFaviconUrl/);
  assert.match(script, /google\.com\/s2\/favicons/);
  assert.match(script, /aria-pressed/);
  assert.match(css, /\.mode-panel\[hidden\]/);
  assert.match(css, /display:\s*none\s*!important/);
  assert.match(css, /\.form-row-main/);
  assert.match(css, /\.form-row-category/);
  assert.match(css, /\.form-row-detail/);
  assert.match(css, /\.field-badge\.required/);
  assert.match(css, /\.field-badge\.optional/);
  assert.match(css, /\.category-manager-list/);
  assert.match(css, /\.category-config-card/);
  assert.match(css, /\.danger-button/);
  assert.match(css, /--control-height:\s*38px/);
  assert.match(css, /white-space:\s*nowrap/);
  assert.match(css, /height:\s*var\(--control-height\)/);
  assert.match(css, /\.axis-options/);
  assert.match(css, /\.axis-option-row/);
  assert.match(css, /\.check-label/);
  assert.match(css, /\.assignment-board/);
  assert.match(css, /\.category-drop-target/);
  assert.match(css, /\.site-source-grid/);
  assert.match(css, /\.site-card/);
  assert.match(css, /\.site-card-body/);
  assert.match(css, /\.site-card-meta/);
  assert.match(css, /\.site-thumbnail/);
  assert.match(css, /\.site-thumbnail\.has-image/);
  assert.match(css, /\.site-source-grid\.list\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/);
  assert.match(css, /\.site-source-grid\.list \.site-card\s*\{[\s\S]*width:\s*100%/);
  assert.match(css, /\.site-source-grid\.list \.site-samples/);
  assert.match(css, /\.rule-card\.list-item/);
  assert.match(css, /\.category-icon\.image/);
});
